# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79377421bdf8c7ab8c25b679d48a5f4039b05ff5a79521ec3d72335828b8d27e10066a4977ee92b6c897c43f82d3b54704aef57e576f17800c1fb4eb2876b93c

test:
  secret_key_base: f8a9276e6260ce58ab7f819cb02fe5c8d16f29765ddd30102b4560824036f06bce19ae451590b14609e40ca50d60a5d7b587805200a5bab2dafeb6483794bee2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
